services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  user-service:
    build: ./user-service
    environment:
      - BLOG_SERVICE_URL=blog-service:8000
      - PORT=8080
    volumes:
      - ./user-service:/app

  blog-service:
    build: ./blog-service
    environment:
      - PORT=8000
    volumes:
      - ./blog-service:/app